# Generated by Django 4.0.3 on 2022-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.CharField(max_length=3)),
            ],
        ),
    ]
