# Generated by Django 4.0.3 on 2022-03-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_image_phone_slug_alter_phone_lte_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.SlugField(),
        ),
    ]
